url = ['https://thenextweb.com/?p=1296657', 'https://indianexpress.com/article/india/up-inspector-suspended-over-convoy-of-vehicles-farewell-6443379/', 'https://indianexpress.com/article/technology/science/how-to-watch-strawberry-moon-eclipse-live-online-6442939/', 'https://indianexpress.com/article/business/companies/abu-dhabi-based-investor-mubadala-to-buy-1-85-stake-in-jio-platforms-for-rs-9093-6-crore-6443419/', 'https://indianexpress.com/article/india/noida-apparel-export-cluster-asks-govt-to-immediately-provide-2-lakh-tailors-staff-6443374/', 'https://indianexpress.com/article/india/up-another-day-of-peak-deaths-30-mortality-in-people-above-50-years-coronavirus-6443369/', 'https://www.cnbctv18.com/market/stocks/10-things-you-need-to-know-before-the-opening-bell-on-june-5-6074441.htm/', 'https://qz.com/africa/1865111/chinese-migrant-workers-in-africa-and-myths-of-self-segregation/', 'https://www.telegraphindia.com/india/trial-casts-doubts-on-malaria-drugs-ability-to-prevent-coronavirus/cid/1778607', 'https://finance.yahoo.com/news/ambani-jio-platforms-sells-1-014946832.html', 'https://www.moneycontrol.com/news/business/markets/what-changed-for-the-market-while-you-were-sleeping-top-10-things-to-know-240-5361751.html', 'https://www.reuters.com/article/india-morningcall-idUSL4N2DI0DT', 'https://www.firstpost.com/entertainment/coronavirus-outbreak-imppa-requests-uddhav-thackeray-to-amend-impractical-guidelines-to-restart-shooting-in-maharashtra-8450671.html', 'https://economictimes.indiatimes.com/markets/stocks/news/stocks-in-the-news-sbi-larsen-toubro-bharti-airtel-dlf-and-infosys/articleshow/76206197.cms', 'https://finance.yahoo.com/news/australia-toughen-foreign-investment-laws-024703398.html', 'https://indianexpress.com/article/world/united-states/chinese-and-iranian-hackers-targeted-biden-and-trump-campaigns-google-says-6443461/', 'https://indianexpress.com/article/india/kanpur-medical-college-principal-removed-after-tablighi-diatribe-video-6443386/', 'https://indianexpress.com/article/entertainment/south-cinema-news-on-june-5-6443444/', 'https://www.business-standard.com/article/economy-policy/top-10-biz-headlines-govt-releases-state-gst-dues-more-investment-in-jio-120060500139_1.html', 'https://indianexpress.com/article/lifestyle/life-positive/world-environment-day-timoci-naulusala-cop23-germany-2017-inspiring-speech-6442610/', 'https://www.freerepublic.com/focus/f-news/3852133/posts']
photo = ['https://img-cdn.tnwcdn.com/image/tnw?filter_last=1&fit=1280%2C640&url=https%3A%2F%2Fcdn0.tnwcdn.com%2Fwp-content%2Fblogs.dir%2F1%2Ffiles%2F2019%2F09%2Fptl-newsletter-hed.png&signature=c4f12fef9a1a81c9ecf46fee2ba1a103', 'https://images.indianexpress.com/2020/06/up-police.jpg?w=759', 'https://images.indianexpress.com/2020/06/moon-delhi.jpg?w=759', 'https://images.indianexpress.com/2020/04/jio-2.jpg?w=759', 'https://images.indianexpress.com/2020/06/read-made.jpg?w=759', 'https://images.indianexpress.com/2020/06/covid-8.jpg?w=759', 'https://images.cnbctv18.com/wp-content/uploads/2018/06/2018-05-11T064134Z_1_LYNXMPEE4A092_RTROPTP_3_MARKETS-SOUTHASIA-STOCKS-768x456.jpg', 'https://cms.qz.com/wp-content/uploads/2020/06/RTX1X4VS-e1591322718548.jpg?quality=75&strip=all&w=1400', 'https://static.telegraphindia.com/derivative/THE_TELEGRAPH/1778607/2X1/derivative2X11591319396857.jpg?v=7', 'https://s.yimg.com/uu/api/res/1.2/0QQeksLpBQdw9yxz40Cofg--~B/aD0xMzM0O3c9MjAwMDtzbT0xO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/bloomberg_markets_842/e53b9a9f881812b8f9607ffb7d2e7dbd', 'https://images.moneycontrol.com/static-mcnews/2018/12/DealingRoom_Sensex_Nifty_Market_Broker-770x433-770x433.jpg', 'https://s4.reutersmedia.net/resources_v2/images/rcom-default.png', 'https://images.firstpost.com/wp-content/uploads/large_file_plugin/2020/05/1590746526_imppa1200.jpg', 'https://img.etimg.com/thumb/msid-76206245,width-1070,height-580,imgsize-436501,overlay-etmarkets/photo.jpg', 'https://s.yimg.com/uu/api/res/1.2/98h8cPs2U_PJ5r5tdSdecw--~B/aD0xMzM0O3c9MjAwMDtzbT0xO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/bloomberg_markets_842/a917152d984aed8af56bfbd83da554c8', 'https://images.indianexpress.com/2016/10/biden-trump-759.jpg?w=759', 'https://images.indianexpress.com/2020/06/aarti.jpg?w=759', 'https://images.indianexpress.com/2020/01/Prasanna-759.jpg?w=759', 'https://bsmedia.business-standard.com/_media/bs/img/article/2020-03/09/full/1583769724-45.jpg', 'https://images.indianexpress.com/2020/06/Timoci-Naulusala_759_COP23.jpg?w=759', None]
title = ['Pardon the Intrusion #19: Paying for Privacy', 'UP: Inspector suspended over convoy of vehicles farewell', 'Lunar Eclipse 2020 Live Stream: How to watch live streaming of Penumbral Lunar Eclipse in India', 'Abu Dhabi-based investor Mubadala to buy 1.85% stake in Jio Platforms for Rs 9093.6 crore', 'Noida apparel export cluster asks govt to immediately provide 2 lakh tailors & staff', 'UP: Another day of peak deaths, 30% mortality in people above 50 years', '10 things you need to know before the opening bell on June 5 - CNBCTV18', 'The truth about Chinese migrants in Africa and their self-segregation', 'Trial casts doubts on malaria drug’s ability to prevent Covid - Telegraph India', 'Ambani’s Jio Platforms Sells $1.2 Billion Stake to Mubadala', 'What changed for the market while you were sleeping? Top 10 things to know', 'Morning News Call - India, June 5', 'Coronavirus Outbreak: IMPPA requests Uddhav Thackeray to amend ‘impractical guidelines’ to restart shooting in Maharashtra', 'Stocks in the news: SBI, RIL, Larsen & Toubro, Bharti Airtel, DLF and Infosys', 'Australia to Toughen Foreign Investment Laws Amid China Spat', 'Chinese and Iranian hackers targeted Biden and Trump campaigns, Google says', 'Kanpur medical college principal removed after Tablighi diatribe video', 'South Cinema news on June 5: Prasanna shares statement on TNEB and more', 'Top 10 biz headlines: Govt releases state GST dues, jobless rate falls', 'World Environment Day: Timoci Naulusala’s 2017 speech is worth revisiting', 'PLEASE DON\x92T GO!']

binded_list=[]
for i in range(0,len(url),3):
    t,ls=0,[]
    k = i
    while t < 3:
        ls.append(url[k+t])
        ls.append(photo[k+t])
        ls.append(title[k+t])
        t+=1
    binded_list.append(ls)

print(binded_list)